from __future__ import annotations

from pathlib import Path
import pandas as pd
import numpy as np


# ============================================================
# CONFIGURATION
# ============================================================

PROJECT_ROOT = Path(__file__).resolve().parents[2]

OUTPUT_DIR = PROJECT_ROOT / "outputs"

FEATURE_DIR = OUTPUT_DIR / "features"
GRAPH_DIR = OUTPUT_DIR / "graph"
MODEL_DIR = OUTPUT_DIR / "models"


# ------------------------------------------------------------
# Files generated by previous layers
# ------------------------------------------------------------
#
# CHANGE ONLY THESE FILENAMES IF YOUR ACTUAL OUTPUT FILENAMES
# ARE DIFFERENT.
# ------------------------------------------------------------

FEATURE_FILE = (
    FEATURE_DIR / "wallet_features.csv"
)

GRAPH_METRICS_FILE = (
    GRAPH_DIR / "graph_metrics.csv"
)

GRAPHSAGE_FILE = (
    GRAPH_DIR / "graphsage_embeddings.csv"
)

ISOLATION_FOREST_FILE = (
    MODEL_DIR / "isolation_forest_scores.csv"
)

AUTOENCODER_FILE = (
    MODEL_DIR / "autoencoder_scores.csv"
)

DETERMINISTIC_FILE = (
    MODEL_DIR / "deterministic_scores.csv"
)


# ============================================================
# HELPERS
# ============================================================

def load_csv(
    path: Path,
    name: str,
) -> pd.DataFrame:

    if not path.exists():

        raise FileNotFoundError(
            f"{name} file not found:\n{path}"
        )

    df = pd.read_csv(path)

    if df.empty:

        raise ValueError(
            f"{name} file is empty:\n{path}"
        )

    if "wallet_id" not in df.columns:

        raise ValueError(
            f"{name} must contain "
            f"'wallet_id'.\n"
            f"Columns found: {list(df.columns)}"
        )

    df["wallet_id"] = (
        df["wallet_id"]
        .astype(str)
    )

    # Prevent accidental duplicate wallet rows.
    if df["wallet_id"].duplicated().any():

        duplicate_count = (
            df["wallet_id"]
            .duplicated()
            .sum()
        )

        raise ValueError(
            f"{name} contains {duplicate_count} "
            "duplicate wallet_id rows. "
            "The fusion layer requires one row "
            "per wallet."
        )

    return df


def keep_numeric_features(
    df: pd.DataFrame,
    source_name: str,
) -> pd.DataFrame:
    """
    Keep wallet_id and numeric columns.

    String metadata such as IPs, transaction IDs,
    countries, etc. should not silently enter the
    numerical ML feature matrix.
    """

    result = pd.DataFrame({
        "wallet_id": df["wallet_id"]
    })

    for column in df.columns:

        if column == "wallet_id":
            continue

        numeric = pd.to_numeric(
            df[column],
            errors="coerce",
        )

        # Keep columns containing at least one
        # numerical observation.
        if numeric.notna().sum() > 0:

            result[column] = numeric

    if len(result.columns) == 1:

        print(
            f"WARNING: {source_name} contains "
            "no numeric features."
        )

    return result


def rename_conflicting_columns(
    df: pd.DataFrame,
    existing_columns: set[str],
    source_name: str,
) -> pd.DataFrame:
    """
    Prevent accidental overwriting when different
    layers use the same feature name.
    """

    rename_map = {}

    for column in df.columns:

        if column == "wallet_id":
            continue

        if column in existing_columns:

            rename_map[column] = (
                f"{source_name}_{column}"
            )

    return df.rename(
        columns=rename_map
    )


def merge_features(
    base: pd.DataFrame,
    additional: pd.DataFrame,
    source_name: str,
) -> pd.DataFrame:

    additional = rename_conflicting_columns(
        additional,
        set(base.columns),
        source_name,
    )

    merged = base.merge(
        additional,
        on="wallet_id",
        how="left",
        validate="one_to_one",
    )

    return merged


# ============================================================
# BASE FEATURE FUSION
# ============================================================

def build_base_fusion() -> pd.DataFrame:
    """
    Creates the feature table used by:

        Isolation Forest
        Autoencoder
        Deterministic Engine

    Components:

        Feature Engineering
        +
        NetworkX metrics
        +
        GraphSAGE embeddings
    """

    print("=" * 60)
    print("BASE FEATURE FUSION")
    print("=" * 60)

    # --------------------------------------------------------
    # 1. Feature engineering
    # --------------------------------------------------------

    base_raw = load_csv(
        FEATURE_FILE,
        "Feature engineering",
    )

    base = keep_numeric_features(
        base_raw,
        "feature_engineering",
    )

    print(
        f"Feature engineering columns: "
        f"{len(base.columns) - 1}"
    )

    # --------------------------------------------------------
    # 2. NetworkX graph metrics
    # --------------------------------------------------------

    graph_raw = load_csv(
        GRAPH_METRICS_FILE,
        "Graph metrics",
    )

    graph = keep_numeric_features(
        graph_raw,
        "networkx",
    )

    base = merge_features(
        base,
        graph,
        "networkx",
    )

    print(
        f"After NetworkX: "
        f"{len(base.columns) - 1} features"
    )

    # --------------------------------------------------------
    # 3. GraphSAGE embeddings
    # --------------------------------------------------------

    sage_raw = load_csv(
        GRAPHSAGE_FILE,
        "GraphSAGE embeddings",
    )

    sage = keep_numeric_features(
        sage_raw,
        "graphsage",
    )

    base = merge_features(
        base,
        sage,
        "graphsage",
    )

    print(
        f"After GraphSAGE: "
        f"{len(base.columns) - 1} features"
    )

    # --------------------------------------------------------
    # Remove all-NaN feature columns
    # --------------------------------------------------------

    feature_columns = [
        c
        for c in base.columns
        if c != "wallet_id"
    ]

    base[feature_columns] = (
        base[feature_columns]
        .replace(
            [np.inf, -np.inf],
            np.nan,
        )
    )

    all_nan = [
        c
        for c in feature_columns
        if base[c].notna().sum() == 0
    ]

    if all_nan:

        base = base.drop(
            columns=all_nan
        )

    # --------------------------------------------------------
    # Fill missing values
    # --------------------------------------------------------

    feature_columns = [
        c
        for c in base.columns
        if c != "wallet_id"
    ]

    base[feature_columns] = (
        base[feature_columns]
        .fillna(0.0)
    )

    # --------------------------------------------------------
    # Remove constant columns
    # --------------------------------------------------------

    constant_columns = [
        c
        for c in feature_columns
        if base[c].nunique(
            dropna=False
        ) <= 1
    ]

    if constant_columns:

        base = base.drop(
            columns=constant_columns
        )

        print(
            f"Removed constant columns: "
            f"{len(constant_columns)}"
        )

    return base


# ============================================================
# ADD MODEL OUTPUTS
# ============================================================

def build_risk_training_features(
    base: pd.DataFrame,
) -> pd.DataFrame:
    """
    Adds outputs from:

        Isolation Forest
        Autoencoder
        Deterministic Engine

    to the base graph/feature representation.

    Ground truth is deliberately NOT included.

    Output:
        risk_training_features.csv
    """

    result = base.copy()

    # --------------------------------------------------------
    # Isolation Forest
    # --------------------------------------------------------

    if_score = load_csv(
        ISOLATION_FOREST_FILE,
        "Isolation Forest",
    )

    if_score = keep_numeric_features(
        if_score,
        "isolation_forest",
    )

    result = merge_features(
        result,
        if_score,
        "isolation_forest",
    )

    print(
        "Added Isolation Forest output."
    )

    # --------------------------------------------------------
    # Autoencoder
    # --------------------------------------------------------

    ae_score = load_csv(
        AUTOENCODER_FILE,
        "Autoencoder",
    )

    ae_score = keep_numeric_features(
        ae_score,
        "autoencoder",
    )

    result = merge_features(
        result,
        ae_score,
        "autoencoder",
    )

    print(
        "Added Autoencoder output."
    )

    # --------------------------------------------------------
    # Deterministic Engine
    # --------------------------------------------------------

    deterministic = load_csv(
        DETERMINISTIC_FILE,
        "Deterministic engine",
    )

    deterministic = keep_numeric_features(
        deterministic,
        "deterministic",
    )

    result = merge_features(
        result,
        deterministic,
        "deterministic",
    )

    print(
        "Added deterministic output."
    )

    # --------------------------------------------------------
    # Final cleanup
    # --------------------------------------------------------

    feature_columns = [
        c
        for c in result.columns
        if c != "wallet_id"
    ]

    result[feature_columns] = (
        result[feature_columns]
        .replace(
            [np.inf, -np.inf],
            np.nan,
        )
        .fillna(0.0)
    )

    return result


# ============================================================
# MAIN
# ============================================================

def main():

    # --------------------------------------------------------
    # Stage 1
    # --------------------------------------------------------

    base = build_base_fusion()

    BASE_OUTPUT = (
        MODEL_DIR
        / "base_fused_features.csv"
    )

    MODEL_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )

    base.to_csv(
        BASE_OUTPUT,
        index=False,
    )

    print(
        f"\nBase fusion saved:\n{BASE_OUTPUT}"
    )

    # --------------------------------------------------------
    # Stage 2
    # --------------------------------------------------------

    final = build_risk_training_features(
        base
    )

    FINAL_OUTPUT = (
        MODEL_DIR
        / "risk_training_features.csv"
    )

    final.to_csv(
        FINAL_OUTPUT,
        index=False,
    )

    # --------------------------------------------------------
    # Summary
    # --------------------------------------------------------

    print("\n" + "=" * 60)
    print("FEATURE FUSION COMPLETE")
    print("=" * 60)

    print(
        f"Wallets: {len(final)}"
    )

    print(
        f"Final features: "
        f"{len(final.columns) - 1}"
    )

    print(
        f"\nBase output:\n"
        f"{BASE_OUTPUT}"
    )

    print(
        f"\nRisk training input:\n"
        f"{FINAL_OUTPUT}"
    )


if __name__ == "__main__":
    main()